version: "3.9"

services:
  nfs-server:
    image: hebertribeiro31/nfs-server:latest
    container_name: nfs-server
    restart: unless-stopped
    privileged: true
    networks:
      docker-fs-net:
        ipv4_address: 172.25.0.50
    volumes:
      - ./nfs-data/nfs.img:/nfs.img   # arquivo persistente

  nfs-client:
    image: alpine:3.20
    container_name: nfs-client
    command: sh -c "apk add --no-cache nfs-utils && mkdir -p /mnt/test && mount -t nfs -o vers=3,nolock 172.25.0.50:/exports/app /mnt/test && tail -f /dev/null"
    privileged: true
    depends_on:
      - nfs-server
    networks:
      docker-fs-net:
        ipv4_address: 172.25.0.60

networks:
  docker-fs-net:
    external: true
